import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Link from 'next/link'
import { cookies } from 'next/headers'
import jwt from 'jsonwebtoken'
import LogoutButton from './components/LogoutButton'
import CartCount from './components/CartCount'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // 쿠키에서 jwt 토큰 획득 (서버 사이드 렌더링)
  const cookieStore = cookies()
  const token = cookieStore.get('auth_token')?.value
  let user: { username: string; role: string } | null = null

  if (token) {
    try {
      const jwtSecret = process.env.JWT_SECRET || 'fallback-secret-string-only-for-development'
      user = jwt.verify(token, jwtSecret) as { username: string; role: string }
    } catch {
      // 무시
    }
  }

  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 통합 글로벌 내비게이션 바 */}
        <header className="sticky top-0 z-50 w-full border-b border-gray-100 bg-white/80 backdrop-blur-md">
          <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
            <div className="flex items-center gap-10">
              <Link
                href="/"
                className="text-2xl font-black tracking-tighter text-blue-600 transition-colors hover:text-blue-700"
              >
                CONNECT
              </Link>
              <nav className="hidden gap-6 text-[0.95rem] font-semibold text-slate-600 md:flex">
                <Link href="#" className="transition hover:text-black">
                  베스트
                </Link>
                <Link href="#" className="transition hover:text-black">
                  신상품
                </Link>
                <Link href="#" className="flex items-center gap-1 text-blue-600 transition hover:text-blue-800">
                  기획전 ⚡
                </Link>
                <Link href="#" className="transition hover:text-black">
                  브랜드
                </Link>
              </nav>
            </div>

            <div className="flex items-center gap-6 text-[0.9rem] font-medium text-slate-600">
              {user ? (
                // 로그인 상태
                <div className="flex items-center gap-5 sm:gap-6">
                  <span className="hidden text-slate-800 sm:inline-block">
                    <strong className="mr-1 font-bold text-black">{user.username}</strong>님
                  </span>
                  <Link
                    href="/mypage"
                    className="relative text-slate-600 transition hover:text-blue-600"
                    title="마이페이지"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth={2}
                      stroke="currentColor"
                      className="h-[1.4rem] w-[1.4rem]"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z"
                      />
                    </svg>
                  </Link>
                  <Link
                    href="/cart"
                    className="relative text-slate-600 transition hover:text-blue-600"
                    title="장바구니"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth={2}
                      stroke="currentColor"
                      className="h-[1.4rem] w-[1.4rem]"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z"
                      />
                    </svg>
                    <span className="absolute -right-2 -top-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-blue-600 text-[10px] font-bold text-white shadow-sm ring-1 ring-white">
                      <CartCount />
                    </span>
                  </Link>
                  <LogoutButton />
                </div>
              ) : (
                // 비로그인 상태
                <div className="flex items-center gap-5 sm:gap-6">
                  <Link
                    href="/cart"
                    className="relative text-slate-600 transition hover:text-blue-600"
                    title="장바구니"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth={2}
                      stroke="currentColor"
                      className="h-[1.4rem] w-[1.4rem]"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z"
                      />
                    </svg>
                    <span className="absolute -right-2 -top-1.5 flex h-4 w-4 items-center justify-center rounded-full bg-blue-600 text-[10px] font-bold text-white shadow-sm ring-1 ring-white">
                      <CartCount />
                    </span>
                  </Link>
                  <Link href="/auth?type=login" className="transition hover:text-black">
                    로그인
                  </Link>
                  <Link href="/auth?type=sign-up" className="transition hover:text-black">
                    회원가입
                  </Link>
                </div>
              )}
            </div>
          </div>
        </header>

        {/* 본문 콘텐츠 영역 */}
        <main>{children}</main>
      </body>
    </html>
  )
}
